### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'process_group'

### ISSUE THREAD

**Issue by Alice-Shen** [facebookresearch/DeeperCluster#14]
I met the problem like this, I don't know what's wrong,could you give me some suggestion?
> Traceback (most recent call last):
  File "main.py", line 254, in <module>
    main(args)
  File "main.py", line 161, in main
    args,
  File "/DeeperCluster/src/model/model_factory.py", line 106, in build_prediction_layer
    pred_layer = to_cuda(pred_layer, args.gpu_to_work_on, group=group)
  File "/DeeperCluster/src/model/model_factory.py", line 123, in to_cuda
    process_group=group,
TypeError: __init__() got an unexpected keyword argument 'process_group'

**Comment by Alice-Shen** [comment]
I have solved the problem by reinstall apex and change pytorch version(0.4->1.0)
