### ISSUE TITLE
type error on own dataset

### ISSUE THREAD

**Issue by juliangaal** [facebookresearch/DeeperCluster#3]
After applying your corrections from #2 , I adapted your code to load my own dataset with pytorchs ImageLoader, which seems to work just fine.  This is my config now:

```bash
INFO - 08/16/19 14:32:30 - 0:00:00 - ============ Initialized logger ============
INFO - 08/16/19 14:32:30 - 0:00:00 - batch_size: 48
                                     checkpoint_freq: 1
                                     clustering_local_rank: 0
                                     clustering_local_world_id: 0
                                     clustering_local_world_size: 1
                                     data_path: /media/linfile1/groups/.../train
                                     dataset: pipes
                                     debug_slurm: False
                                     dim_pca: 2048
                                     dist_url: file:///media/linfile1/groups/.../sharedfs
                                     dump_checkpoints: /media/linfile1/groups/.../exp2019-08-16_12-31-55/checkpoints
                                     dump_path: /media/linfile1/groups.../exp2019-08-16_12-31-55
                                     epoch: 0
                                     epoch_size: 17568
                                     gpu_to_work_on: 0
                                     is_slurm_job: False
                                     k: 105
                                     local_rank: -1
                                     lr: 0.1
                                     nepochs: 100
                                     niter: 10
                                     nmb_super_clusters: 1
                                     pretrained:
                                     rank: 0
                                     reassignment: 3
                                     rotation: 0
                                     rotnet: False
                                     size_dataset: 70416
                                     sobel: True
                                     start_iter: 0
                                     super_classes: 1
                                     training_local_rank: 0
                                     training_local_world_id: 0
                                     training_local_world_size: 1
                                     use_faiss: True
                                     warm_restart: False
                                     wd: 0.0001
                                     workers: 10
                                     world_size: 1
```

Just before epoch 2 however, I'm getting a type error after running though almost an entire epoch (the dataset is garbage at the moment, still just a test run):

```bash
INFO - 08/16/19 14:32:30 - 0:00:00 - The experiment will be stored in /media/.../exp2019-08-16_12-31-55


Signal handler installed.
INFO - 08/16/19 14:32:32 - 0:00:02 - model created
INFO - 08/16/19 14:32:32 - 0:00:02 - pretrained weights not found
Warning:  using Python fallback for SyncBatchNorm, possibly because apex was installed without --cuda_ext.  The exception raised when attempting to import the cuda backend was:  No module named 'syncbn'
Warning:  apex was installed without --cpp_ext.  Falling back to Python flatten and unflatten.
INFO - 08/16/19 14:32:36 - 0:00:05 - model to cuda
INFO - 08/16/19 14:32:36 - 0:00:05 - ============ Starting epoch 0 ... ============
INFO - 08/16/19 14:32:36 - 0:00:05 - => Start clustering step
INFO - 08/16/19 14:32:36 - 0:00:05 - Require 8386560 images (174720 iterations) for pca
WARNING - 08/16/19 14:32:36 - 0:00:05 - Compute the PCA on 70416 images (entire dataset)
INFO - 08/16/19 14:32:37 - 0:00:07 - 0 / 1467   Time: 1.849 (1.849)     Data Time: 1.361 (1.361)
INFO - 08/16/19 14:33:17 - 0:00:47 - 200 / 1467 Time: 0.200 (0.208)     Data Time: 0.000 (0.007)
INFO - 08/16/19 14:33:57 - 0:01:27 - 400 / 1467 Time: 0.200 (0.204)     Data Time: 0.000 (0.004)
INFO - 08/16/19 14:34:37 - 0:02:07 - 600 / 1467 Time: 0.200 (0.203)     Data Time: 0.000 (0.002)
INFO - 08/16/19 14:35:17 - 0:02:47 - 800 / 1467 Time: 0.201 (0.202)     Data Time: 0.000 (0.002)
INFO - 08/16/19 14:35:57 - 0:03:27 - 1000 / 1467        Time: 0.200 (0.202)     Data Time: 0.000 (0.002)
INFO - 08/16/19 14:36:37 - 0:04:07 - 1200 / 1467        Time: 0.199 (0.201)     Data Time: 0.000 (0.001)
INFO - 08/16/19 14:37:17 - 0:04:47 - 1400 / 1467        Time: 0.199 (0.201)     Data Time: 0.000 (0.001)
WARNING - 08/16/19 14:37:37 - 0:05:06 - keeping 98.86 % of the energy
INFO - 08/16/19 14:37:41 - 0:05:11 - 70416 imgs cached => cache is 100.00 % full
INFO - 08/16/19 14:37:42 - 0:05:12 - Pass[0] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:42 - 0:05:12 -  # Pass[0] Time 1.019      Loss 1.9465
INFO - 08/16/19 14:37:43 - 0:05:13 - Pass[1] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:43 - 0:05:13 -  # Pass[1] Time 0.977      Loss 0.9388
INFO - 08/16/19 14:37:44 - 0:05:14 - Pass[2] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:44 - 0:05:14 -  # Pass[2] Time 0.977      Loss 0.9388
INFO - 08/16/19 14:37:45 - 0:05:15 - Pass[3] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:45 - 0:05:15 -  # Pass[3] Time 0.974      Loss 0.9388
INFO - 08/16/19 14:37:46 - 0:05:15 - Pass[4] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:46 - 0:05:16 -  # Pass[4] Time 0.973      Loss 0.9388
INFO - 08/16/19 14:37:47 - 0:05:16 - Pass[5] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:47 - 0:05:17 -  # Pass[5] Time 0.976      Loss 0.9388
INFO - 08/16/19 14:37:48 - 0:05:17 - Pass[6] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:48 - 0:05:18 -  # Pass[6] Time 0.973      Loss 0.9388
INFO - 08/16/19 14:37:49 - 0:05:18 - Pass[7] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:49 - 0:05:19 -  # Pass[7] Time 0.971      Loss 0.9388
INFO - 08/16/19 14:37:50 - 0:05:19 - Pass[8] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:50 - 0:05:20 -  # Pass[8] Time 0.971      Loss 0.9388
INFO - 08/16/19 14:37:51 - 0:05:20 - Pass[9] - Iter: [1000/1467]        Time 0.001 (0.001)
INFO - 08/16/19 14:37:51 - 0:05:21 -  # Pass[9] Time 0.974      Loss 0.9388
INFO - 08/16/19 14:37:52 - 0:05:21 - Pass[10] - Iter: [1000/1467]       Time 0.001 (0.001)
INFO - 08/16/19 14:37:52 - 0:05:22 -  # Pass[10]        Time 0.974      Loss 0.9388
tensor([    0,     1,     2,  ..., 70413, 70414, 70415], dtype=torch.int32)
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    main(args)
  File "main.py", line 203, in main
    cluster_assignments = get_cluster_assignments(args, model, dataset, clustering_groups)
  File ".../src/clustering.py", line 82, in get_cluster_assignments
    where_helper = get_indices_sparse(super_class_assignements[indices])
  File ".../src/utils.py", line 354, in get_indices_sparse
    M = compute_M(data)
  File ".../src/utils.py", line 351, in compute_M
    shape=(data.max() + 1, data.size))
  File ".../lib/python3.7/site-packages/scipy/sparse/compressed.py", line 57, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File ".../lib/python3.7/site-packages/scipy/sparse/coo.py", line 156, in __init__
    self._shape = check_shape((M, N))
  File ".../lib/python3.7/site-packages/scipy/sparse/sputils.py", line 279, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File ".../lib/python3.7/site-packages/scipy/sparse/sputils.py", line 279, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

Any idea where the error could come from?

**Comment by mathildecaron31** [comment]
Hi, try to replace `shape=(data.max() + 1, data.size))` with `shape=(int(data.max()) + 1, data.size))` [here](https://github.com/facebookresearch/DeeperCluster/blob/b71e62936ce6e20cbe9695c016237f17ac6fc330/src/utils.py#L351)

**Comment by juliangaal** [comment]
I'll check it out Monday, thanks!

Works perfectly, thanks a lot!
