### ISSUE TITLE
Any way to reduce/limit memory usage?

### ISSUE THREAD

**Issue by juliangaal** [facebookresearch/DeeperCluster#4]
I'm getting this error on epoch 13
```
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    main(args)
  File "main.py", line 230, in main
    scores = train_network(args, models, optimizers, dataset)
  File ../src/trainer.py", line 156, in train_network
    loss.backward()
  File ".../dev/miniconda/envs/deepcluster/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File ".../dev/miniconda/envs/deepcluster/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File ".../dev/miniconda/envs/deepcluster/lib/python3.7/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File ".../dev/miniconda/envs/deepcluster/lib/python3.7/site-packages/apex/parallel/sync_batchnorm_kernel.py", line 78, in backward
    running_variance + eps) * c_last_grad).view(-1, num_features).sum(0)
RuntimeError: CUDA out of memory. Tried to allocate 598.62 MiB (GPU 0; 11.91 GiB total capacity; 6.25 GiB already allocated; 573.38 MiB free; 4.37 GiB cached)
```
I think this has something to do with the number of clusters used? I increased the number from 105 in the test run to 300 something in this (and the past) run. Possible hurdle: I use the python lib of apex without pure C++ cuda bindings

This was my full config, still local, single GPU (P100)
```bash
INFO - 08/20/19 07:26:12 - 0:00:00 - ============ Initialized logger ============
INFO - 08/20/19 07:26:12 - 0:00:00 - batch_size: 48
                                     checkpoint_freq: 1
                                     clustering_local_rank: 0
                                     clustering_local_world_id: 0
                                     clustering_local_world_size: 1
                                     data_path: .../data/.../train
                                     debug_slurm: False
                                     dim_pca: 4096
                                     dist_url: file:///.../data/Full_National/sharedfsv2
                                     dump_checkpoints: .../.../exp2019-08-20_05-26-04/checkpoints
                                     dump_path: .../.../exp2019-08-20_05-26-04
                                     epoch: 0
                                     epoch_size: 17568
                                     gpu_to_work_on: 0
                                     is_slurm_job: False
                                     k: 300
                                     local_rank: -1
                                     lr: 0.1
                                     nepochs: 100
                                     niter: 10
                                     nmb_super_clusters: 1
                                     pretrained:
                                     rank: 0
                                     reassignment: 3
                                     rotation: 0
                                     rotnet: False
                                     size_dataset: 70416
                                     sobel: True
                                     start_iter: 0
                                     super_classes: 1
                                     training_local_rank: 0
                                     training_local_world_id: 0
                                     training_local_world_size: 1
                                     use_faiss: True
                                     warm_restart: False
                                     wd: 0.0001
                                     workers: 8
                                     world_size: 1

```

If you need more output, let me know.

**Comment by mathildecaron31** [comment]
Hi, if it doesn't fit in GPU memory you can either reduce the batch size or the number of clusters.

**Comment by juliangaal** [comment]
Doing that results in other errors, which I am not sure about. Often times at around epoch 8-12:
```bash
Traceback (most recent call last):
  File "deepcluster/core/main.py", line 251, in <module>
    main(args)
  File "deepcluster/core/main.py", line 230, in main
    scores = train_network(args, models, optimizers, dataset)
  File "/.../src/trainer.py", line 96, in train_network
    seed=args.epoch + args.training_local_world_id,
  File "/.../src/trainer.py", line 61, in __init__
    replace=(len(label_indexes) <= per_label)
ValueError: could not broadcast input array from shape (122) into shape (0)
```
Looking at your code, the only way this is possible is if this random numpy array has shape 0? Or can `epoch_indexes[....]` have 0 elements? 
```bash
epoch_indexes[k * per_label: (k + 1) * per_label] = np.random.choice(
       label_indexes,
       per_label,
       replace=(len(label_indexes) <= per_label)
 )
```
per label can never be 0, from my understanding
```bash
# number of images per label
per_label = int(self.total_size // nmb_pseudo_lab + 1)
```
`k` can become zero, which isn't a problem because the end index is `k+1`.

in this case `label_indices` must be 0, because `np.random.choice` 
> Generate a uniform random sample from np.arange(<label_indices>) with <per_label> elements

When can this problem appear? Thanks for your help

EDIT: this issue may or may not be related to your suggestion above. Still, playing with differing cluster sizes seems to cause this issue

**Comment by juliangaal** [comment]
Just made it to epoch 54, want access to the full log file?  Errored with the same error

**Comment by mathildecaron31** [comment]
Hi,
From the error message it seems that `epoch_indexes[k * per_label: (k + 1) * per_label]` is an empty array. I think this might be because you have empty clusters (thus some k are bigger than `nmb_pseudo_lab`)

**Comment by mathildecaron31** [comment]
should be fixed here:
https://github.com/facebookresearch/DeeperCluster/commit/7a4699b2bfd13788a116763acc1f063cadd1a886
Please reopen if this still happens
